defaults:
  - env/cosmos_libero_spatial@env.train
  - env/libero_spatial@env.eval
  - model/pi0_5@actor.model
  - training_backend/fsdp@actor.fsdp_config
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/

cluster:
  num_nodes: 1
  component_placement:
    actor,env,rollout: all

runner:
  task_type: embodied
  logger:
    log_path: "../results"
    project_name: rlinf
    experiment_name: "cosmos_libero_spatial_grpo_openpi05"
    logger_backends: ["tensorboard"] # wandb, swanlab

  max_epochs: 1000
  max_steps: -1

  only_eval: False
  val_check_interval: -1
  save_interval: 1

  resume_dir: null
  ckpt_path: null

algorithm:
  normalize_advantages: True
  kl_penalty: kl
  group_size: 8
  reward_coef: 5.0
  rollout_epoch: 8
  eval_rollout_epoch: 1

  reward_type: chunk_level
  logprob_type: chunk_level
  entropy_type: token_level
  update_epoch: 1

  adv_type: grpo
  loss_type: actor
  loss_agg_func: "token-mean"
  kl_beta: 0.0
  entropy_bonus: 0
  clip_ratio_high: 0.2
  clip_ratio_low: 0.2
  clip_ratio_c: 3.0
  value_clip: 0.2
  huber_delta: 10.0

  gamma: 0.99
  gae_lambda: 0.95

  filter_rewards: True
  rewards_lower_bound: 0.5
  rewards_upper_bound: 4.5

  # params for generation
  sampling_params:
    do_sample: True
    temperature_train: 1.0
    temperature_eval: 0.6
    top_k: 50
    top_p: 1.0
    repetition_penalty: 1.0
    add_BOS: False

  # length argument for autoregressive sampling
  length_params:
    max_new_token: null
    max_length: 1024
    min_length: 1

env:
  group_name: "EnvGroup"
  enable_offload: True # otherwise, may OOM with world model

  # Override the default values in env/cosmos_libero_spatial
  train:
    total_num_envs: 64
    group_size: ${algorithm.group_size}
    max_episode_steps: 256 # max episode steps for truncation (must be divisible by num_action_chunks=8)
    max_steps_per_rollout_epoch: 256
    reward_coef: ${algorithm.reward_coef}
    reset_gripper_open: False
    opensora_wm_hf_ckpt_path: "./models/RLinf-OpenSora-LIBERO-Spatial"
    cosmos_ckpt_path: "./models/Cosmos-Predict2.5-LIBERO-Spatial/libero-spatial-2b-19k.pt"
  eval:
    total_num_envs: 100
    auto_reset: True
    ignore_terminations: True
    max_episode_steps: 512
    max_steps_per_rollout_epoch: 512
    group_size: 1
    reset_gripper_open: False
    is_eval: True
    video_cfg:
      save_video: True
      video_base_dir: ${runner.logger.log_path}/video/eval

rollout:
  group_name: "RolloutGroup"
  generation_backend: "huggingface"
  recompute_logprobs: False
  unnorm_key: libero_10
  enable_offload: True
  pipeline_stage_num: 1

  model:
    model_path: "./models/RLinf-Pi05-LIBERO-SFT"
    precision: ${actor.model.precision}

actor:
  group_name: "ActorGroup"
  training_backend: "fsdp"
  micro_batch_size: 128
  global_batch_size: 2048
  seed: 42
  enable_offload: True

  model:
    model_path: "./models/RLinf-Pi05-LIBERO-SFT"
    num_action_chunks: 8 # must match world model chunk size (8)
    num_steps: 3

  optim:
    lr: 5.0e-6
    value_lr: 1.0e-4
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
    weight_decay: 0.01
    clip_grad: 1.0

  fsdp_config:
    strategy: "fsdp"
    sharding_strategy: "no_shard"
    gradient_checkpointing: False
    mixed_precision:
      param_dtype: ${actor.model.precision}
      reduce_dtype: ${actor.model.precision}
      buffer_dtype: ${actor.model.precision}

reward:
  use_reward_model: False

critic:
  use_critic_model: False
