model_type: "mlp_policy"

model_path: ""

policy_setup: "panda-qpos"
obs_dim: 42
action_dim: 8
num_action_chunks: 1
hidden_dim: 256

precision: "32"
add_value_head: True

is_lora: False
lora_rank: 32
