env_type: frankasim
gym_id: PandaPickCube-v0


obs_mode: state
obs_format: tensor
state_key: state
render: false

seed: 0
total_num_envs: null
group_size: 1

auto_reset: True
ignore_terminations: False
max_steps_per_rollout_epoch: 200
max_episode_steps: 200

use_rel_reward: True
reward_coef: 1.0
is_eval: False

video_cfg:
  save_video: False
  info_on_video: True
  video_base_dir: ${runner.logger.log_path}/video/train
