env_type: maniskill

total_num_envs: null

auto_reset: False
ignore_terminations: False
use_rel_reward: True
seed: 0
group_size: 1
use_fixed_reset_state_ids: True
max_steps_per_rollout_epoch: 80
max_episode_steps: 80 # max episode steps for truncation

video_cfg:
  save_video: False
  info_on_video: True
  video_base_dir: ${runner.logger.log_path}/video/train

init_params:
  id: PutOnPlateInScene25Main-v3
  num_envs: null # will be set in ManiSkillEnv init
  obs_mode: "rgb+segmentation"
  control_mode: None
  sim_backend: "gpu"
  sim_config:
    sim_freq: 500
    control_freq: 5
  max_episode_steps: ${env.train.max_episode_steps} # max episode steps for truncation
  sensor_configs:
    shader_pack: "default"
  render_mode: all
  obj_set: train
  use_multiple_plates: False   # turn to true for openpi experiments