env_type: robocasa

# Robot configuration
robot_name: PandaOmron

# Camera configuration
# Pi0 model uses two 128x128 cameras: left view and wrist view
camera_names:
  - robot0_agentview_left
  - robot0_eye_in_hand

# Task configuration (simplified atomic tasks)
task_names:
  # - OpenSingleDoor
  # - TurnOnSinkFaucet
  - CloseDrawer

total_num_envs: null

auto_reset: False
ignore_terminations: False
max_steps_per_rollout_epoch: 300
max_episode_steps: 300 # max episode steps for truncation
use_fixed_reset_state_ids: False
use_ordered_reset_state_ids: False

use_rel_reward: True
reward_coef: 1.0
is_eval: False

seed: 0
group_size: 1

video_cfg:
  save_video: False
  info_on_video: True
  video_base_dir: ${runner.logger.log_path}/video/train

init_params:
  camera_heights: 224
  camera_widths: 224
